package HelloApp;


/**
* HelloApp/HelloOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Hello.idl
* Tuesday, March 31, 2015 8:33:33 AM CST
*/

public interface HelloOperations 
{
  String judgeInt (String inStr);
  void shutdown ();
} // interface HelloOperations
